var classes = [
    {
        "name": "App\\Helpers\\DateHelper",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "formatIndonesia",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "formatShort",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "formatLong",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Carbon\\Carbon"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 23,
        "vocabulary": 11,
        "volume": 79.57,
        "difficulty": 4.86,
        "effort": 386.47,
        "level": 0.21,
        "bugs": 0.03,
        "time": 21,
        "intelligentContent": 16.38,
        "number_operators": 6,
        "number_operands": 17,
        "number_operators_unique": 4,
        "number_operands_unique": 7,
        "cloc": 20,
        "loc": 40,
        "lloc": 20,
        "mi": 102.5,
        "mIwoC": 58.04,
        "commentWeight": 44.46,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.87,
        "relativeSystemComplexity": 16.87,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 2.6,
        "totalSystemComplexity": 50.6,
        "package": "App\\Helpers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\AdminController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "dashboard",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showLoginForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Product",
            "App\\Models\\User",
            "App\\Models\\Order",
            "App\\Models\\Order",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\User",
            "Illuminate\\Http\\Request",
            "App\\Models\\User",
            "App\\Models\\User"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 7,
        "length": 90,
        "vocabulary": 39,
        "volume": 475.69,
        "difficulty": 5.22,
        "effort": 2483.36,
        "level": 0.19,
        "bugs": 0.16,
        "time": 138,
        "intelligentContent": 91.12,
        "number_operators": 19,
        "number_operands": 71,
        "number_operators_unique": 5,
        "number_operands_unique": 34,
        "cloc": 17,
        "loc": 76,
        "lloc": 59,
        "mi": 75.66,
        "mIwoC": 42.22,
        "commentWeight": 33.44,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 484,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 484.42,
        "totalStructuralComplexity": 3388,
        "totalDataComplexity": 2.96,
        "totalSystemComplexity": 3390.96,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\AuthController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "showLoginForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showRegisterForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\Models\\User",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 5,
        "length": 61,
        "vocabulary": 25,
        "volume": 283.28,
        "difficulty": 4.67,
        "effort": 1321.95,
        "level": 0.21,
        "bugs": 0.09,
        "time": 73,
        "intelligentContent": 60.7,
        "number_operators": 12,
        "number_operands": 49,
        "number_operators_unique": 4,
        "number_operands_unique": 21,
        "cloc": 13,
        "loc": 54,
        "lloc": 41,
        "mi": 81.7,
        "mIwoC": 47.24,
        "commentWeight": 34.45,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.45,
        "relativeSystemComplexity": 256.45,
        "totalStructuralComplexity": 1280,
        "totalDataComplexity": 2.24,
        "totalSystemComplexity": 1282.24,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\BankController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Bank",
            "Illuminate\\Http\\Request",
            "App\\Models\\Bank",
            "Illuminate\\Http\\Request",
            "App\\Models\\Bank",
            "App\\Models\\Bank"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 55,
        "vocabulary": 17,
        "volume": 224.81,
        "difficulty": 3.33,
        "effort": 749.37,
        "level": 0.3,
        "bugs": 0.07,
        "time": 42,
        "intelligentContent": 67.44,
        "number_operators": 5,
        "number_operands": 50,
        "number_operators_unique": 2,
        "number_operands_unique": 15,
        "cloc": 12,
        "loc": 38,
        "lloc": 26,
        "mi": 90.77,
        "mIwoC": 52.53,
        "commentWeight": 38.23,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.56,
        "relativeSystemComplexity": 64.56,
        "totalStructuralComplexity": 256,
        "totalDataComplexity": 2.22,
        "totalSystemComplexity": 258.22,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\CartController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "view",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buyNow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "midtransCallback",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProductQuantity",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateQuantity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "payment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "processPayment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 39,
        "ccn": 29,
        "ccnMethodMax": 8,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Services\\CartService",
            "App\\Services\\OrderService",
            "App\\Services\\ProductService",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Bank",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 287,
        "vocabulary": 72,
        "volume": 1770.77,
        "difficulty": 16.69,
        "effort": 29560.41,
        "level": 0.06,
        "bugs": 0.59,
        "time": 1642,
        "intelligentContent": 106.08,
        "number_operators": 80,
        "number_operands": 207,
        "number_operators_unique": 10,
        "number_operands_unique": 62,
        "cloc": 57,
        "loc": 209,
        "lloc": 152,
        "mi": 61.94,
        "mIwoC": 25.76,
        "commentWeight": 36.18,
        "kanDefect": 1.2,
        "relativeStructuralComplexity": 576,
        "relativeDataComplexity": 1.1,
        "relativeSystemComplexity": 577.1,
        "totalStructuralComplexity": 6336,
        "totalDataComplexity": 12.08,
        "totalSystemComplexity": 6348.08,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 5,
        "lloc": 4,
        "mi": 202.94,
        "mIwoC": 171,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.06,
        "afferentCoupling": 12,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\KategoriController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 6,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Kategori",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Kategori",
            "App\\Models\\Kategori",
            "Illuminate\\Support\\Facades\\Storage",
            "Illuminate\\Support\\Facades\\Storage",
            "Illuminate\\Http\\Request",
            "App\\Models\\Kategori",
            "Illuminate\\Support\\Facades\\Storage",
            "Illuminate\\Support\\Facades\\Storage"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 78,
        "vocabulary": 23,
        "volume": 352.84,
        "difficulty": 8.47,
        "effort": 2989.32,
        "level": 0.12,
        "bugs": 0.12,
        "time": 166,
        "intelligentContent": 41.65,
        "number_operators": 17,
        "number_operands": 61,
        "number_operators_unique": 5,
        "number_operands_unique": 18,
        "cloc": 11,
        "loc": 52,
        "lloc": 41,
        "mi": 78.86,
        "mIwoC": 46.17,
        "commentWeight": 32.69,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.36,
        "relativeSystemComplexity": 169.36,
        "totalStructuralComplexity": 676,
        "totalDataComplexity": 1.43,
        "totalSystemComplexity": 677.43,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\OrderController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "order",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "history",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "order_detail_user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "detail_order",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "confirmPayment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rejectPayment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reports",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cancelledOrders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Cart",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Order",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Order",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Order",
            "App\\Models\\Order",
            "App\\Models\\Order",
            "Illuminate\\Http\\Request",
            "App\\Models\\Order",
            "Illuminate\\Http\\Request",
            "App\\Models\\Order",
            "Illuminate\\Http\\Request",
            "App\\Models\\Order",
            "App\\Models\\Order"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 10,
        "length": 137,
        "vocabulary": 49,
        "volume": 769.22,
        "difficulty": 7.88,
        "effort": 6064.28,
        "level": 0.13,
        "bugs": 0.26,
        "time": 337,
        "intelligentContent": 97.57,
        "number_operators": 24,
        "number_operands": 113,
        "number_operators_unique": 6,
        "number_operands_unique": 43,
        "cloc": 10,
        "loc": 79,
        "lloc": 69,
        "mi": 65.19,
        "mIwoC": 39.01,
        "commentWeight": 26.18,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 529,
        "relativeDataComplexity": 0.45,
        "relativeSystemComplexity": 529.45,
        "totalStructuralComplexity": 5290,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 5294.5,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\PageController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "about",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "product_page",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Kategori",
            "App\\Models\\Product",
            "App\\Models\\Product",
            "Illuminate\\Http\\Request",
            "App\\Models\\Kategori",
            "App\\Models\\Product",
            "App\\Models\\Product"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 52,
        "vocabulary": 15,
        "volume": 203.16,
        "difficulty": 4.88,
        "effort": 990.4,
        "level": 0.21,
        "bugs": 0.07,
        "time": 55,
        "intelligentContent": 41.67,
        "number_operators": 13,
        "number_operands": 39,
        "number_operators_unique": 3,
        "number_operands_unique": 12,
        "cloc": 9,
        "loc": 39,
        "lloc": 30,
        "mi": 85.08,
        "mIwoC": 51.22,
        "commentWeight": 33.87,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.52,
        "relativeSystemComplexity": 36.52,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 1.57,
        "totalSystemComplexity": 109.57,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ProductController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findKategori",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleImageUpload",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteImage",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Kategori",
            "App\\Models\\Product",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Product",
            "Illuminate\\Http\\Request",
            "App\\Models\\Product",
            "App\\Models\\Product",
            "App\\Models\\Kategori",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Storage",
            "Illuminate\\Support\\Facades\\Storage"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 133,
        "vocabulary": 39,
        "volume": 702.96,
        "difficulty": 7.94,
        "effort": 5582.32,
        "level": 0.13,
        "bugs": 0.23,
        "time": 310,
        "intelligentContent": 88.52,
        "number_operators": 25,
        "number_operands": 108,
        "number_operators_unique": 5,
        "number_operands_unique": 34,
        "cloc": 12,
        "loc": 71,
        "lloc": 59,
        "mi": 70.23,
        "mIwoC": 40.49,
        "commentWeight": 29.74,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 441,
        "relativeDataComplexity": 0.45,
        "relativeSystemComplexity": 441.45,
        "totalStructuralComplexity": 3528,
        "totalDataComplexity": 3.64,
        "totalSystemComplexity": 3531.64,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ProfileController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "profile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "adminProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProfile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProfileAdmin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Hash"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 70,
        "vocabulary": 19,
        "volume": 297.35,
        "difficulty": 6.8,
        "effort": 2022.01,
        "level": 0.15,
        "bugs": 0.1,
        "time": 112,
        "intelligentContent": 43.73,
        "number_operators": 19,
        "number_operands": 51,
        "number_operators_unique": 4,
        "number_operands_unique": 15,
        "cloc": 10,
        "loc": 51,
        "lloc": 41,
        "mi": 78.64,
        "mIwoC": 46.96,
        "commentWeight": 31.67,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.79,
        "relativeSystemComplexity": 36.79,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 3.14,
        "totalSystemComplexity": 147.14,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\SolidCartController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "view",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buyNow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateQuantity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "payment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "processPayment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 30,
        "ccn": 22,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Services\\CartService",
            "App\\Services\\OrderService",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Bank",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 210,
        "vocabulary": 51,
        "volume": 1191.21,
        "difficulty": 11.93,
        "effort": 14213.29,
        "level": 0.08,
        "bugs": 0.4,
        "time": 790,
        "intelligentContent": 99.83,
        "number_operators": 60,
        "number_operands": 150,
        "number_operators_unique": 7,
        "number_operands_unique": 44,
        "cloc": 50,
        "loc": 173,
        "lloc": 123,
        "mi": 66.91,
        "mIwoC": 29.91,
        "commentWeight": 36.99,
        "kanDefect": 0.92,
        "relativeStructuralComplexity": 484,
        "relativeDataComplexity": 1.14,
        "relativeSystemComplexity": 485.14,
        "totalStructuralComplexity": 4356,
        "totalDataComplexity": 10.3,
        "totalSystemComplexity": 4366.3,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\SolidOrderController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "history",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "orderDetailUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "adminIndex",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "adminShow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getByStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "statistics",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 21,
        "ccn": 15,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Services\\OrderService",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 141,
        "vocabulary": 43,
        "volume": 765.1,
        "difficulty": 8.19,
        "effort": 6265.58,
        "level": 0.12,
        "bugs": 0.26,
        "time": 348,
        "intelligentContent": 93.43,
        "number_operators": 40,
        "number_operands": 101,
        "number_operators_unique": 6,
        "number_operands_unique": 37,
        "cloc": 41,
        "loc": 133,
        "lloc": 92,
        "mi": 72.85,
        "mIwoC": 34.95,
        "commentWeight": 37.9,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.99,
        "relativeSystemComplexity": 289.99,
        "totalStructuralComplexity": 2312,
        "totalDataComplexity": 7.89,
        "totalSystemComplexity": 2319.89,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\SolidProductController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "adminIndex",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "lowStock",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 17,
        "ccn": 11,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Services\\ProductService",
            "Illuminate\\Http\\Request",
            "App\\Models\\Kategori",
            "App\\Models\\Kategori",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 156,
        "vocabulary": 41,
        "volume": 835.78,
        "difficulty": 6.43,
        "effort": 5376.09,
        "level": 0.16,
        "bugs": 0.28,
        "time": 299,
        "intelligentContent": 129.93,
        "number_operators": 37,
        "number_operands": 119,
        "number_operators_unique": 4,
        "number_operands_unique": 37,
        "cloc": 42,
        "loc": 129,
        "lloc": 87,
        "mi": 74.41,
        "mIwoC": 35.75,
        "commentWeight": 38.66,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 1.05,
        "relativeSystemComplexity": 226.05,
        "totalStructuralComplexity": 1800,
        "totalDataComplexity": 8.44,
        "totalSystemComplexity": 1808.44,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Models\\Bank",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 0,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 0,
        "effort": 0,
        "level": 1.67,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 7,
        "lloc": 7,
        "mi": 73.42,
        "mIwoC": 73.42,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Models\\",
        "pageRank": 0.04,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Models\\Cart",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "products",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 5,
        "volume": 13.93,
        "difficulty": 0.63,
        "effort": 8.71,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 22.29,
        "number_operators": 1,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 10,
        "lloc": 10,
        "mi": 70.04,
        "mIwoC": 70.04,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\Models\\",
        "pageRank": 0.1,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "App\\Models\\Kategori",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getGambarUrlAttribute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "products",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model",
            "Illuminate\\Support\\Facades\\Storage"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 2,
        "length": 19,
        "vocabulary": 12,
        "volume": 68.11,
        "difficulty": 2.17,
        "effort": 147.58,
        "level": 0.46,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 31.44,
        "number_operators": 6,
        "number_operands": 13,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 5,
        "loc": 26,
        "lloc": 21,
        "mi": 89.33,
        "mIwoC": 57.92,
        "commentWeight": 31.42,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 9.75,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 19.5,
        "package": "App\\Models\\",
        "pageRank": 0.06,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Models\\Order",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "items",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bank",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 2,
        "length": 18,
        "vocabulary": 12,
        "volume": 64.53,
        "difficulty": 0.68,
        "effort": 44,
        "level": 1.47,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 94.64,
        "number_operators": 3,
        "number_operands": 15,
        "number_operators_unique": 1,
        "number_operands_unique": 11,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 59.81,
        "mIwoC": 59.81,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 15,
        "package": "App\\Models\\",
        "pageRank": 0.09,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "App\\Models\\OrderItem",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "products",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "order",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 0.8,
        "effort": 20.68,
        "level": 1.25,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 32.31,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 2,
        "loc": 16,
        "lloc": 14,
        "mi": 91.01,
        "mIwoC": 64.97,
        "commentWeight": 26.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "package": "App\\Models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Models\\Product",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getGambarUrlAttribute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "kategori",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model",
            "Illuminate\\Support\\Facades\\Storage"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "implements": [],
        "lcom": 2,
        "length": 25,
        "vocabulary": 15,
        "volume": 97.67,
        "difficulty": 2.25,
        "effort": 219.76,
        "level": 0.44,
        "bugs": 0.03,
        "time": 12,
        "intelligentContent": 43.41,
        "number_operators": 7,
        "number_operands": 18,
        "number_operators_unique": 3,
        "number_operands_unique": 12,
        "cloc": 5,
        "loc": 30,
        "lloc": 25,
        "mi": 84.73,
        "mIwoC": 55.17,
        "commentWeight": 29.56,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 10,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 30,
        "package": "App\\Models\\",
        "pageRank": 0.11,
        "afferentCoupling": 7,
        "efferentCoupling": 2,
        "instability": 0.22,
        "violations": {}
    },
    {
        "name": "App\\Models\\User",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "casts",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "carts",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "orders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "parents": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "implements": [],
        "lcom": 2,
        "length": 18,
        "vocabulary": 12,
        "volume": 64.53,
        "difficulty": 0.68,
        "effort": 44,
        "level": 1.47,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 94.64,
        "number_operators": 3,
        "number_operands": 15,
        "number_operators_unique": 1,
        "number_operands_unique": 11,
        "cloc": 17,
        "loc": 36,
        "lloc": 19,
        "mi": 103.03,
        "mIwoC": 59.3,
        "commentWeight": 43.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 7.5,
        "package": "App\\Models\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AppServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "implements": [],
        "lcom": 2,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 8,
        "loc": 18,
        "lloc": 10,
        "mi": 213.94,
        "mIwoC": 171,
        "commentWeight": 42.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\RepositoryServiceProvider",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "implements": [],
        "lcom": 2,
        "length": 4,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 11,
        "loc": 25,
        "lloc": 14,
        "mi": 213.8,
        "mIwoC": 171,
        "commentWeight": 42.8,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 2,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repositories\\CachedProductRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "getAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findById",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Contracts\\ReadProductRepositoryInterface",
            "App\\Models\\Product",
            "Illuminate\\Support\\Facades\\Cache",
            "App\\Models\\Product",
            "Illuminate\\Support\\Facades\\Cache"
        ],
        "parents": [],
        "implements": [
            "App\\Contracts\\ReadProductRepositoryInterface"
        ],
        "lcom": 2,
        "length": 14,
        "vocabulary": 6,
        "volume": 36.19,
        "difficulty": 1,
        "effort": 36.19,
        "level": 1,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 36.19,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 10,
        "loc": 26,
        "lloc": 16,
        "mi": 103.67,
        "mIwoC": 62.69,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.9,
        "relativeSystemComplexity": 16.9,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1.8,
        "totalSystemComplexity": 33.8,
        "package": "App\\Repositories\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repositories\\CartRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getByUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateQuantity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clearCart",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTotalPrice",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getItemsCount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 10,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Contracts\\CartRepositoryInterface",
            "App\\Models\\Cart",
            "Illuminate\\Database\\Eloquent\\Collection",
            "App\\Models\\Cart"
        ],
        "parents": [],
        "implements": [
            "App\\Contracts\\CartRepositoryInterface"
        ],
        "lcom": 1,
        "length": 95,
        "vocabulary": 22,
        "volume": 423.65,
        "difficulty": 13.69,
        "effort": 5798.65,
        "level": 0.07,
        "bugs": 0.14,
        "time": 322,
        "intelligentContent": 30.95,
        "number_operators": 22,
        "number_operands": 73,
        "number_operators_unique": 6,
        "number_operands_unique": 16,
        "cloc": 4,
        "loc": 57,
        "lloc": 53,
        "mi": 63.4,
        "mIwoC": 43.45,
        "commentWeight": 19.95,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.89,
        "relativeSystemComplexity": 121.89,
        "totalStructuralComplexity": 968,
        "totalDataComplexity": 7.08,
        "totalSystemComplexity": 975.08,
        "package": "App\\Repositories\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repositories\\OrderRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findById",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getByUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getByStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPaginated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 7,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Contracts\\OrderRepositoryInterface",
            "App\\Models\\Order",
            "App\\Models\\Order",
            "Illuminate\\Database\\Eloquent\\Collection",
            "Illuminate\\Database\\Eloquent\\Collection",
            "Illuminate\\Pagination\\LengthAwarePaginator"
        ],
        "parents": [],
        "implements": [
            "App\\Contracts\\OrderRepositoryInterface"
        ],
        "lcom": 1,
        "length": 54,
        "vocabulary": 17,
        "volume": 220.72,
        "difficulty": 4.61,
        "effort": 1016.9,
        "level": 0.22,
        "bugs": 0.07,
        "time": 56,
        "intelligentContent": 47.91,
        "number_operators": 11,
        "number_operands": 43,
        "number_operators_unique": 3,
        "number_operands_unique": 14,
        "cloc": 4,
        "loc": 42,
        "lloc": 38,
        "mi": 71.86,
        "mIwoC": 48.86,
        "commentWeight": 23,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.74,
        "relativeSystemComplexity": 100.74,
        "totalStructuralComplexity": 700,
        "totalDataComplexity": 5.18,
        "totalSystemComplexity": 705.18,
        "package": "App\\Repositories\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Repositories\\ProductRepository",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAll",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPaginated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findById",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getByCategory",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "searchByName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLowStock",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "delete",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStock",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 10,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 13,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Contracts\\ProductRepositoryInterface",
            "App\\Models\\Product",
            "Illuminate\\Database\\Eloquent\\Collection",
            "Illuminate\\Pagination\\LengthAwarePaginator",
            "Illuminate\\Database\\Eloquent\\Collection",
            "Illuminate\\Database\\Eloquent\\Collection",
            "Illuminate\\Database\\Eloquent\\Collection",
            "App\\Models\\Product"
        ],
        "parents": [],
        "implements": [
            "App\\Contracts\\ProductRepositoryInterface"
        ],
        "lcom": 1,
        "length": 80,
        "vocabulary": 23,
        "volume": 361.88,
        "difficulty": 6.21,
        "effort": 2247.5,
        "level": 0.16,
        "bugs": 0.12,
        "time": 125,
        "intelligentContent": 58.27,
        "number_operators": 21,
        "number_operands": 59,
        "number_operators_unique": 4,
        "number_operands_unique": 19,
        "cloc": 7,
        "loc": 69,
        "lloc": 62,
        "mi": 66.13,
        "mIwoC": 42.45,
        "commentWeight": 23.68,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 122.17,
        "totalStructuralComplexity": 1331,
        "totalDataComplexity": 12.92,
        "totalSystemComplexity": 1343.92,
        "package": "App\\Repositories\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Services\\CartService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addToCart",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateQuantity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeFromCart",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCartItems",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCartTotal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCartItemsCount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clearCart",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateCartStock",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Contracts\\CartRepositoryInterface",
            "App\\Services\\ProductService",
            "App\\Models\\Cart",
            "Exception",
            "Exception",
            "Exception",
            "Illuminate\\Database\\Eloquent\\Collection"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 91,
        "vocabulary": 19,
        "volume": 386.56,
        "difficulty": 9.33,
        "effort": 3607.91,
        "level": 0.11,
        "bugs": 0.13,
        "time": 200,
        "intelligentContent": 41.42,
        "number_operators": 21,
        "number_operands": 70,
        "number_operators_unique": 4,
        "number_operands_unique": 15,
        "cloc": 34,
        "loc": 97,
        "lloc": 63,
        "mi": 81.39,
        "mIwoC": 41.69,
        "commentWeight": 39.69,
        "kanDefect": 0.73,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.89,
        "relativeSystemComplexity": 121.89,
        "totalStructuralComplexity": 1089,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 1097,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 2,
        "efferentCoupling": 5,
        "instability": 0.71,
        "violations": {}
    },
    {
        "name": "App\\Services\\OrderService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createOrderFromCart",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createDirectOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUserOrders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateOrderStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrdersByStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllOrders",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 6,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Contracts\\OrderRepositoryInterface",
            "App\\Contracts\\CartRepositoryInterface",
            "App\\Services\\ProductService",
            "App\\Models\\Order",
            "Exception",
            "Exception",
            "App\\Models\\OrderItem",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Order",
            "Exception",
            "App\\Models\\OrderItem",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Database\\Eloquent\\Collection",
            "Illuminate\\Database\\Eloquent\\Collection"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 132,
        "vocabulary": 31,
        "volume": 653.95,
        "difficulty": 8,
        "effort": 5231.63,
        "level": 0.13,
        "bugs": 0.22,
        "time": 291,
        "intelligentContent": 81.74,
        "number_operators": 24,
        "number_operands": 108,
        "number_operators_unique": 4,
        "number_operands_unique": 27,
        "cloc": 38,
        "loc": 109,
        "lloc": 71,
        "mi": 78.71,
        "mIwoC": 39.1,
        "commentWeight": 39.62,
        "kanDefect": 0.82,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.71,
        "relativeSystemComplexity": 196.71,
        "totalStructuralComplexity": 1568,
        "totalDataComplexity": 5.67,
        "totalSystemComplexity": 1573.67,
        "package": "App\\Services\\",
        "pageRank": 0.02,
        "afferentCoupling": 3,
        "efferentCoupling": 8,
        "instability": 0.73,
        "violations": {}
    },
    {
        "name": "App\\Services\\ProductService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllProducts",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPaginatedProducts",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteProduct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasStock",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStock",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLowStockProducts",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "uploadProductImage",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 10,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 19,
        "ccn": 10,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Contracts\\ProductRepositoryInterface",
            "Illuminate\\Database\\Eloquent\\Collection",
            "App\\Models\\Product",
            "Illuminate\\Support\\Facades\\Storage",
            "Illuminate\\Support\\Facades\\Storage",
            "Illuminate\\Database\\Eloquent\\Collection",
            "Illuminate\\Http\\UploadedFile"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 107,
        "vocabulary": 23,
        "volume": 484.02,
        "difficulty": 10.69,
        "effort": 5176.34,
        "level": 0.09,
        "bugs": 0.16,
        "time": 288,
        "intelligentContent": 45.26,
        "number_operators": 30,
        "number_operands": 77,
        "number_operators_unique": 5,
        "number_operands_unique": 18,
        "cloc": 42,
        "loc": 118,
        "lloc": 76,
        "mi": 78.74,
        "mIwoC": 38.83,
        "commentWeight": 39.91,
        "kanDefect": 0.71,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 1.04,
        "relativeSystemComplexity": 197.04,
        "totalStructuralComplexity": 2156,
        "totalDataComplexity": 11.4,
        "totalSystemComplexity": 2167.4,
        "package": "App\\Services\\",
        "pageRank": 0.03,
        "afferentCoupling": 4,
        "efferentCoupling": 5,
        "instability": 0.56,
        "violations": {}
    }
]